import type { ZoningWorksheet } from '@/lib/zoning/types';

const now = new Date('2026-05-08T12:00:00.000Z');

export const workbookReferenceNotes = {
  file: 'docs/reference/zoning/1760 Jerome Ave Zoning 241101.xlsx',
  observedSheets: [
    'R8A-UG2-Special District',
    'Area Tabulation (A)',
    'UNIT DISTRIBUTION',
    'UGIIIA NET AREAS',
    'MIH RECALIBRATION STUDIES 11-1',
    'Base Plane Calculation',
  ],
  workflowSummary:
    'Workbook separates a primary zoning-compliance worksheet from supporting floor-area, unit-distribution, net-area, MIH, and base-plane calculation sheets.',
};

export const mockZoningWorksheet: ZoningWorksheet = {
  report: {
    id: 'zoning-1760-jerome',
    projectId: 'mock-project',
    title: 'Zoning Research Worksheet',
    address: '1760 Jerome Ave, Bronx, NY 10453',
    borough: 'Bronx',
    block: '2850',
    lot: '3 & 7',
    zoningDistrict: 'R8A',
    commercialOverlay: 'C2-4',
    specialDistrict: 'Special Jerome Corridor District',
    createdAt: now,
    updatedAt: now,
  },
  sections: [
    {
      id: 'lot-identity',
      reportId: 'zoning-1760-jerome',
      key: 'lot_identity',
      title: 'Lot Identity',
      description: 'Core zoning lot facts, address, map, lot assembly, and review assumptions.',
      sortOrder: 1,
      items: [
        {
          id: 'address',
          reportId: 'zoning-1760-jerome',
          section: 'lot_identity',
          field: 'Address',
          value: '1760 Jerome Ave, Bronx, NY 10453',
          source: 'Project record / workbook reference',
          status: 'auto_filled',
          notes: 'Project address should become the default seed for future lookup integrations.',
          createdAt: now,
        },
        {
          id: 'block-lot',
          reportId: 'zoning-1760-jerome',
          section: 'lot_identity',
          field: 'Block / Lot',
          value: 'Block 2850, Lots 3 & 7',
          source: 'Workbook zoning information',
          status: 'auto_filled',
          notes: 'Workbook notes existing tax lots are treated as one zoning lot assumption.',
          createdAt: now,
        },
        {
          id: 'lot-area',
          reportId: 'zoning-1760-jerome',
          section: 'lot_identity',
          field: 'Lot Area',
          value: '14,000 sf',
          source: 'Workbook lot area row',
          status: 'calculated',
          notes: 'Corner and interior lot portions are separated in the workbook.',
          createdAt: now,
        },
        {
          id: 'zoning-lot-merger',
          reportId: 'zoning-1760-jerome',
          section: 'lot_identity',
          field: 'Zoning Lot Merger',
          value: 'Assumed combined zoning lot',
          source: 'Architect review',
          status: 'manual_review_required',
          notes: 'Confirm title, tax lot merger, zoning lot description, and supporting survey exhibits.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'districts-overlays',
      reportId: 'zoning-1760-jerome',
      key: 'districts_overlays',
      title: 'Zoning Districts & Overlays',
      description: 'District, overlay, MIH, transit-zone, and environmental-designation context.',
      sortOrder: 2,
      items: [
        {
          id: 'district',
          reportId: 'zoning-1760-jerome',
          section: 'districts_overlays',
          field: 'Zoning District',
          value: 'R8A',
          source: 'Zoning map 3d / workbook',
          status: 'auto_filled',
          notes: 'Future lookup should preserve the review source and map date.',
          createdAt: now,
        },
        {
          id: 'overlay',
          reportId: 'zoning-1760-jerome',
          section: 'districts_overlays',
          field: 'Commercial Overlay',
          value: 'C2-4',
          source: 'Workbook zoning district row',
          status: 'auto_filled',
          createdAt: now,
        },
        {
          id: 'special-district',
          reportId: 'zoning-1760-jerome',
          section: 'districts_overlays',
          field: 'Special District',
          value: 'Special Jerome Corridor District',
          source: 'ZR 141 / workbook',
          status: 'manual_review_required',
          notes: 'Workbook treats this as a separate special-district review layer.',
          createdAt: now,
        },
        {
          id: 'mih',
          reportId: 'zoning-1760-jerome',
          section: 'districts_overlays',
          field: 'Housing Designation',
          value: 'Mandatory Inclusionary Housing Area',
          source: 'Workbook zoning information',
          status: 'guidance',
          notes: 'Option selection and income bands require human confirmation.',
          createdAt: now,
        },
        {
          id: 'transit-zone',
          reportId: 'zoning-1760-jerome',
          section: 'districts_overlays',
          field: 'Transit Zone',
          value: 'Bronx Community District 5 transit zone',
          source: 'ZR Appendix I / workbook',
          status: 'guidance',
          notes: 'Impacts parking assumptions; confirm current zoning text.',
          createdAt: now,
        },
        {
          id: 'e-designation',
          reportId: 'zoning-1760-jerome',
          section: 'districts_overlays',
          field: 'E-Designation',
          value: 'E-442',
          source: 'CEQR and application references in workbook',
          status: 'manual_review_required',
          notes: 'Hazardous materials, window-wall attenuation, and ventilation requirements need separate consultant review.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'floor-area',
      reportId: 'zoning-1760-jerome',
      key: 'floor_area',
      title: 'Floor Area',
      description: 'FAR, zoning floor area, MIH area, and deductions drawn from the workbook tabulation pattern.',
      sortOrder: 3,
      items: [
        {
          id: 'max-far',
          reportId: 'zoning-1760-jerome',
          section: 'floor_area',
          field: 'Maximum Residential FAR',
          value: '7.2',
          source: 'ZR 141-22 / workbook FAR section',
          status: 'guidance',
          notes: 'Dependent on district, MIH, and applicable special district provisions.',
          createdAt: now,
        },
        {
          id: 'proposed-far',
          reportId: 'zoning-1760-jerome',
          section: 'floor_area',
          field: 'Proposed FAR',
          value: '3.59',
          source: 'Workbook FAR section',
          status: 'calculated',
          notes: 'Example uses worksheet area values, not live project geometry.',
          createdAt: now,
        },
        {
          id: 'max-zfa',
          reportId: 'zoning-1760-jerome',
          section: 'floor_area',
          field: 'Maximum Zoning Floor Area',
          value: '100,800 sf',
          source: '14,000 sf x 7.2',
          status: 'calculated',
          createdAt: now,
        },
        {
          id: 'mih-required',
          reportId: 'zoning-1760-jerome',
          section: 'floor_area',
          field: 'MIH Floor Area',
          value: 'Option 1 review required',
          source: 'Workbook MIH rows and recalibration sheet',
          status: 'manual_review_required',
          notes: 'Income band, affordable floor-area factor, and unit mix require review against current HPD/MIH program assumptions.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'use-regulations',
      reportId: 'zoning-1760-jerome',
      key: 'use_regulations',
      title: 'Use Regulations',
      description: 'Use group review follows the workbook distinction between residential, community facility, and ground-floor use constraints.',
      sortOrder: 4,
      items: [
        {
          id: 'res-use',
          reportId: 'zoning-1760-jerome',
          section: 'use_regulations',
          field: 'Residential Use',
          value: 'Use Group II multifamily residential',
          source: 'ZR 22-00 / workbook',
          status: 'guidance',
          createdAt: now,
        },
        {
          id: 'cf-use',
          reportId: 'zoning-1760-jerome',
          section: 'use_regulations',
          field: 'Community Facility Use',
          value: 'Use Group IIIA supportive housing component',
          source: 'ZR 32-00 / workbook',
          status: 'guidance',
          notes: 'Confirm use classification and nonprofit sleeping-accommodation assumptions.',
          createdAt: now,
        },
        {
          id: 'ground-floor',
          reportId: 'zoning-1760-jerome',
          section: 'use_regulations',
          field: 'Ground Floor Frontage',
          value: 'Special district active-use frontage review',
          source: 'ZR 141-32 / workbook',
          status: 'manual_review_required',
          notes: 'Lobby width, depth, and transparency should be checked against drawings.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'yard-requirements',
      reportId: 'zoning-1760-jerome',
      key: 'yard_requirements',
      title: 'Yard Requirements',
      description: 'Yard review includes corner-lot and interior-lot distinctions rather than one flat rule.',
      sortOrder: 5,
      items: [
        {
          id: 'front-yard',
          reportId: 'zoning-1760-jerome',
          section: 'yard_requirements',
          field: 'Front Yard',
          value: 'N/A',
          source: 'ZR 23-45 / workbook',
          status: 'guidance',
          createdAt: now,
        },
        {
          id: 'rear-yard',
          reportId: 'zoning-1760-jerome',
          section: 'yard_requirements',
          field: 'Rear Yard',
          value: "30'-0\" minimum at interior lot portion",
          source: 'ZR 23-47 / workbook',
          status: 'guidance',
          notes: "Workbook notes no rear yard required within 100' of corner.",
          createdAt: now,
        },
        {
          id: 'window-distance',
          reportId: 'zoning-1760-jerome',
          section: 'yard_requirements',
          field: 'Window to Lot Line Distance',
          value: "30'-0\"",
          source: 'ZR 23-861 / workbook',
          status: 'calculated',
          notes: 'Drawing confirmation required before reporting compliance.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'height-setback',
      reportId: 'zoning-1760-jerome',
      key: 'height_setback',
      title: 'Height & Setback',
      description: 'Base plane, street wall, base height, maximum height, story count, and articulation review.',
      sortOrder: 6,
      items: [
        {
          id: 'base-plane',
          reportId: 'zoning-1760-jerome',
          section: 'height_setback',
          field: 'Base Plane Elevation',
          value: 'TBD after survey',
          source: 'ZR 12-10 / workbook',
          status: 'manual_review_required',
          notes: 'Workbook has a separate Base Plane Calculation sheet, reinforcing manual survey dependency.',
          createdAt: now,
        },
        {
          id: 'max-height',
          reportId: 'zoning-1760-jerome',
          section: 'height_setback',
          field: 'Maximum Building Height',
          value: "165'-0\" permitted / 136'-8\" proposed",
          source: 'ZR 141-23(b) / workbook',
          status: 'calculated',
          createdAt: now,
        },
        {
          id: 'stories',
          reportId: 'zoning-1760-jerome',
          section: 'height_setback',
          field: 'Maximum Stories',
          value: '16 permitted / 14 proposed',
          source: 'ZR 141-23(b) / workbook',
          status: 'calculated',
          createdAt: now,
        },
        {
          id: 'articulation',
          reportId: 'zoning-1760-jerome',
          section: 'height_setback',
          field: 'Street Wall Articulation',
          value: 'Projection/recess review required',
          source: 'ZR 141-23 / workbook',
          status: 'manual_review_required',
          notes: 'Workbook separates elevated-rail frontage articulation from general street-wall review.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'parking',
      reportId: 'zoning-1760-jerome',
      key: 'parking',
      title: 'Parking',
      description: 'Accessory vehicle parking, bicycle parking, and transit-zone assumptions.',
      sortOrder: 7,
      items: [
        {
          id: 'res-parking',
          reportId: 'zoning-1760-jerome',
          section: 'parking',
          field: 'Residential Parking',
          value: 'None required for income-restricted housing units in transit zone',
          source: 'ZR 36-35 / 25-251 / workbook',
          status: 'guidance',
          notes: 'Confirm unit restrictions and transit zone applicability.',
          createdAt: now,
        },
        {
          id: 'bike-res',
          reportId: 'zoning-1760-jerome',
          section: 'parking',
          field: 'Bicycle Parking - UG II',
          value: '34 spaces required / 38 proposed',
          source: '1 per 2 dwelling units',
          status: 'calculated',
          createdAt: now,
        },
        {
          id: 'bike-cf',
          reportId: 'zoning-1760-jerome',
          section: 'parking',
          field: 'Bicycle Parking - UG IIIA',
          value: '5 spaces required',
          source: '1 per 10,000 sf',
          status: 'calculated',
          createdAt: now,
        },
      ],
    },
    {
      id: 'special-district-review',
      reportId: 'zoning-1760-jerome',
      key: 'special_district',
      title: 'Special District / Manual Review',
      description: 'Human review queue for conditions that depend on drawings, interpretation, and source confirmation.',
      sortOrder: 8,
      items: [
        {
          id: 'quality-housing',
          reportId: 'zoning-1760-jerome',
          section: 'special_district',
          field: 'Quality Housing',
          value: 'Multiple sections apply',
          source: 'ZR 28 series / workbook',
          status: 'manual_review_required',
          notes: 'Refuse, laundry, corridor daylight, recreation space, planting, and density each require drawing review.',
          createdAt: now,
        },
        {
          id: 'frontage-interpretation',
          reportId: 'zoning-1760-jerome',
          section: 'special_district',
          field: 'Frontage Interpretation',
          value: 'Elevated rail frontage condition',
          source: 'ZR 141-23(c)',
          status: 'manual_review_required',
          notes: 'Confirm which street-wall frontage conditions are triggered.',
          createdAt: now,
        },
        {
          id: 'irregular-lot',
          reportId: 'zoning-1760-jerome',
          section: 'special_district',
          field: 'Irregular Lot Assumptions',
          value: 'Review against survey',
          source: 'Architect review',
          status: 'manual_review_required',
          notes: 'Lot coverage, yards, and base plane should all trace back to survey geometry.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'legal-references',
      reportId: 'zoning-1760-jerome',
      key: 'legal_references',
      title: 'Legal References',
      description: 'Citations and source anchors used in the worksheet.',
      sortOrder: 9,
      items: [
        {
          id: 'zr-reference',
          reportId: 'zoning-1760-jerome',
          section: 'legal_references',
          field: 'Applicable Resolution',
          value: 'Zoning Resolution of the City of New York',
          source: 'Workbook header',
          status: 'auto_filled',
          createdAt: now,
        },
        {
          id: 'primary-sections',
          reportId: 'zoning-1760-jerome',
          section: 'legal_references',
          field: 'Primary ZR Sections',
          value: '12-10, 23-154, 23-47, 28 series, 36 series, 141 series',
          source: 'Workbook citations',
          status: 'guidance',
          notes: 'Citations should become structured references in saved reports.',
          createdAt: now,
        },
      ],
    },
    {
      id: 'export-summary',
      reportId: 'zoning-1760-jerome',
      key: 'export_summary',
      title: 'Export Summary',
      description: 'Report-ready summary language and unresolved review items.',
      sortOrder: 10,
      items: [
        {
          id: 'report-summary',
          reportId: 'zoning-1760-jerome',
          section: 'export_summary',
          field: 'Draft Summary',
          value: 'R8A/C2-4 mixed-use zoning review with Special Jerome Corridor District overlays',
          source: 'Workbook summary pattern',
          status: 'guidance',
          notes: 'Narrative should be reviewed by project architect before issue.',
          createdAt: now,
        },
        {
          id: 'export-status',
          reportId: 'zoning-1760-jerome',
          section: 'export_summary',
          field: 'Export Readiness',
          value: 'Manual review open',
          source: 'System review queue',
          status: 'manual_review_required',
          notes: 'Export remains placeholder until persistence and report generation are added.',
          createdAt: now,
        },
      ],
    },
  ],
  manualFlags: [
    {
      id: 'flag-base-plane',
      reportId: 'zoning-1760-jerome',
      title: 'Base plane depends on survey source points',
      description: 'The workbook isolates base plane calculations on a separate sheet. Treat base plane as a survey-backed manual review item until source points are confirmed.',
      severity: 'high',
      reference: 'ZR 12-10',
    },
    {
      id: 'flag-special-district',
      reportId: 'zoning-1760-jerome',
      title: 'Special district interpretation is not deterministic',
      description: 'Street-wall, frontage, transparency, and elevated-rail provisions require architectural drawing review and zoning interpretation.',
      severity: 'high',
      reference: 'ZR 141',
    },
    {
      id: 'flag-mih',
      reportId: 'zoning-1760-jerome',
      title: 'MIH assumptions require program confirmation',
      description: 'Income bands, floor area, and unit distribution should be coordinated with current HPD and project program assumptions.',
      severity: 'medium',
      reference: 'ZR 23-154',
    },
    {
      id: 'flag-edesc',
      reportId: 'zoning-1760-jerome',
      title: 'E-designation consultant items remain outside zoning automation',
      description: 'Hazardous materials, attenuation, and ventilation requirements should be tracked as due diligence items, not automated compliance conclusions.',
      severity: 'medium',
      reference: 'E-442',
    },
  ],
  references: [
    {
      id: 'ref-workbook',
      reportId: 'zoning-1760-jerome',
      label: '1760 Jerome Ave zoning workbook',
      source: 'Uploaded Excel workbook',
      notes: 'Primary workflow and terminology reference for this first zoning module pass.',
    },
    {
      id: 'ref-zr',
      reportId: 'zoning-1760-jerome',
      label: 'NYC Zoning Resolution',
      source: 'NYC Department of City Planning',
      notes: 'Future integration should store section-level citations and retrieval dates.',
    },
    {
      id: 'ref-pluto',
      reportId: 'zoning-1760-jerome',
      label: 'PLUTO / MapPLUTO',
      source: 'NYC Open Data / NYC Planning',
      notes: 'Future source for lot facts, district information, and property metadata.',
    },
  ],
};
