import type { ZoningReportItem, ZoningSectionKey, ZoningWorksheet } from '@/lib/zoning/types';

const now = new Date('2026-05-08T12:00:00.000Z');
const reportId = 'zoning-1760-jerome';

export const workbookReferenceNotes = {
  file: 'docs/reference/zoning/1760 Jerome Ave Zoning 241101.xlsx',
  observedSheets: [
    'R8A-UG2-Special District',
    'Area Tabulation (A)',
    'UNIT DISTRIBUTION',
    'UGIIIA NET AREAS',
    'MIH RECALIBRATION STUDIES 11-1',
    'Base Plane Calculation',
  ],
  workflowSummary:
    'Workbook separates a primary zoning-compliance worksheet from supporting floor-area, unit-distribution, net-area, MIH, and base-plane calculation sheets.',
};

type WorkbookRowInput = {
  id: string;
  section: ZoningSectionKey;
  zrSection?: string;
  itemDescription: string;
  permittedRequired: string;
  proposed?: string;
  result?: ZoningReportItem['result'];
  status?: ZoningReportItem['status'];
  evaluationMode?: ZoningReportItem['evaluationMode'];
  source?: string;
  notes?: string;
};

function row(input: WorkbookRowInput): ZoningReportItem {
  return {
    id: input.id,
    reportId,
    section: input.section,
    field: input.itemDescription,
    value: input.permittedRequired,
    zrSection: input.zrSection,
    itemDescription: input.itemDescription,
    permittedRequired: input.permittedRequired,
    proposed: input.proposed,
    result: input.result ?? (input.proposed ? 'complies' : 'incomplete'),
    evaluationMode: input.evaluationMode ?? (input.proposed ? 'formula_check' : 'manual_input'),
    source: input.source ?? 'Workbook reference',
    status: input.status ?? (input.proposed ? 'calculated' : 'guidance'),
    notes: input.notes,
    createdAt: now,
  };
}

export const mockZoningWorksheet: ZoningWorksheet = {
  report: {
    id: reportId,
    projectId: 'mock-project',
    title: 'Zoning Research Worksheet',
    address: '1760 Jerome Ave, Bronx, NY 10453',
    borough: 'Bronx',
    block: '2850',
    lot: '3 & 7',
    zoningDistrict: 'R8A',
    commercialOverlay: 'C2-4',
    specialDistrict: 'Special Jerome Corridor District',
    createdAt: now,
    updatedAt: now,
  },
  sections: [
    {
      id: 'zoning-information',
      reportId,
      key: 'zoning_information',
      title: 'Zoning Information',
      description: 'Address-driven facts that should be auto-filled from parcel and zoning datasets.',
      sortOrder: 1,
      items: [
        row({
          id: 'applicable-resolution',
          section: 'zoning_information',
          itemDescription: 'Applicable Resolution',
          permittedRequired: 'Zoning Resolution of the City of New York',
          result: 'manual_review_required',
          status: 'guidance',
          evaluationMode: 'lookup_only',
          notes: 'Use current Zoning Resolution text for final citations.',
        }),
        row({
          id: 'address',
          section: 'zoning_information',
          itemDescription: 'Address',
          permittedRequired: '1760 Jerome Ave, Bronx, NY 10453',
          result: 'manual_review_required',
          status: 'auto_filled',
          evaluationMode: 'lookup_only',
        }),
        row({
          id: 'block-lot',
          section: 'zoning_information',
          itemDescription: 'Block / Lot(s)',
          permittedRequired: 'Block 2850, Lots 3 & 7. Existing tax lots are treated as one zoning lot assumption.',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
          notes: 'Confirm tax lot merger, zoning lot description, title, and survey exhibits.',
        }),
        row({
          id: 'zoning-district',
          section: 'zoning_information',
          itemDescription: 'Zoning District',
          permittedRequired: 'R8A / C2-4 in Special Jerome Corridor District',
          result: 'manual_review_required',
          status: 'auto_filled',
          evaluationMode: 'lookup_only',
          source: 'Zoning map / district lookup',
        }),
        row({
          id: 'zoning-map',
          section: 'zoning_information',
          itemDescription: 'Zoning Map',
          permittedRequired: '3d',
          result: 'manual_review_required',
          status: 'auto_filled',
          evaluationMode: 'lookup_only',
        }),
        row({
          id: 'housing-designation',
          section: 'zoning_information',
          itemDescription: 'Housing Designation',
          permittedRequired: 'Mandatory Inclusionary Housing Area (MIH)',
          result: 'manual_review_required',
          status: 'guidance',
          evaluationMode: 'manual_review',
        }),
        row({
          id: 'transit-designation',
          section: 'zoning_information',
          itemDescription: 'Transit Designation',
          permittedRequired: 'Bronx Community District 5 Transit Zone',
          result: 'manual_review_required',
          status: 'guidance',
          evaluationMode: 'lookup_only',
          source: 'ZR Appendix I / workbook reference',
        }),
        row({
          id: 'lot-area',
          section: 'zoning_information',
          itemDescription: 'Lot Area',
          permittedRequired: '14,000 sf. Corner lot portion: 5,000 sf. Interior lot portion: 9,000 sf.',
          result: 'manual_review_required',
          status: 'calculated',
          evaluationMode: 'formula_check',
          notes: 'Lot dimensions and portions should trace back to survey or parcel geometry.',
        }),
      ],
    },
    {
      id: 'uses',
      reportId,
      key: 'use_regulations',
      title: 'Uses',
      description: 'Use classification and special district frontage controls.',
      sortOrder: 2,
      items: [
        row({
          id: 'uses-res-cf',
          section: 'use_regulations',
          zrSection: '22-00 / 32-00',
          itemDescription: 'Permitted uses',
          permittedRequired: 'Use Groups II and IIIA',
          proposed: '',
          result: 'incomplete',
          evaluationMode: 'manual_input',
          notes: 'Proposed use should be entered by the architect before evaluating.',
        }),
        row({
          id: 'ground-floor-frontage',
          section: 'use_regulations',
          zrSection: '141-32',
          itemDescription: 'Ground floor level street frontage near elevated rail structure',
          permittedRequired:
            'Primary street frontage ground floor uses are limited to non-residential uses except permitted lobby conditions; glazing must be reviewed under Section 37-34.',
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
          notes: 'Requires drawing review for lobby, depth, frontage, and transparency.',
        }),
      ],
    },
    {
      id: 'far',
      reportId,
      key: 'far',
      title: 'FAR',
      description: 'FAR limits and proposed FAR comparisons.',
      sortOrder: 3,
      items: [
        row({
          id: 'far-residential',
          section: 'far',
          zrSection: '141-22',
          itemDescription: 'Residential',
          permittedRequired: '7.20',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'far-base',
          section: 'far',
          zrSection: '141-04 / 35-31 / 23-154(b)',
          itemDescription: 'Base FAR',
          permittedRequired: '5.40',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'far-low-income',
          section: 'far',
          zrSection: '23-154(b) & (d)(2)',
          itemDescription: 'Max FAR with low income floor area',
          permittedRequired: '7.20',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'far-community-facility',
          section: 'far',
          zrSection: '35-31 / 33-012 / 33-121 / 23-153',
          itemDescription: 'Community facility nonprofit with sleeping accommodations (UG-IIIA)',
          permittedRequired: '6.02',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
      ],
    },
    {
      id: 'floor-area',
      reportId,
      key: 'floor_area',
      title: 'Floor Area',
      description: 'Maximum permitted floor area, use allocation, and MIH floor area calculations.',
      sortOrder: 4,
      items: [
        row({
          id: 'max-floor-area',
          section: 'floor_area',
          zrSection: '141-22',
          itemDescription: 'Maximum permitted for zoning lot',
          permittedRequired: '14,000 sf x 7.2 = 100,800 sf',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'cf-floor-area',
          section: 'floor_area',
          itemDescription: 'Community facility nonprofit with sleeping accommodations',
          permittedRequired: '14,000 sf x 6.02 = 84,280 sf',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'ug-ii-available',
          section: 'floor_area',
          itemDescription: 'Max UG-II available after UG-IIIA deducted',
          permittedRequired: '100,800 sf - proposed UG-IIIA floor area',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'mih-required',
          section: 'floor_area',
          zrSection: '23-154(d)(2)',
          itemDescription: 'Minimum affordable housing floor area required',
          permittedRequired: 'Option and income bands determine required MIH floor area.',
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
          notes: 'Income bands and MIH option require architect/program review.',
        }),
      ],
    },
    {
      id: 'lot-coverage',
      reportId,
      key: 'lot_coverage',
      title: 'Lot Coverage',
      description: 'Corner and interior lot coverage checks.',
      sortOrder: 5,
      items: [
        row({
          id: 'coverage-corner',
          section: 'lot_coverage',
          zrSection: '23-153',
          itemDescription: 'Maximum for corner lot portion',
          permittedRequired: '5,000 sf x 100% = 5,000 sf',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'coverage-interior',
          section: 'lot_coverage',
          zrSection: '23-153',
          itemDescription: 'Maximum for interior lot portion',
          permittedRequired: '9,000 sf x 70% = 6,300 sf',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'coverage-total',
          section: 'lot_coverage',
          itemDescription: 'Total lot coverage permitted',
          permittedRequired: '5,000 sf + 6,300 sf = 11,300 sf',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
      ],
    },
    {
      id: 'lot-area-du',
      reportId,
      key: 'lot_area_du',
      title: 'Lot Area / DU',
      description: 'Dwelling unit factor and unit-count checks.',
      sortOrder: 6,
      items: [
        row({
          id: 'du-factor',
          section: 'lot_area_du',
          zrSection: '23-24',
          itemDescription: 'Dwelling unit factor',
          permittedRequired: '(100,800 sf - proposed non-residential floor area) / 680',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
      ],
    },
    {
      id: 'yard',
      reportId,
      key: 'yard_requirements',
      title: 'Yard',
      description: 'Front, side, rear yard, and window-to-lot-line checks.',
      sortOrder: 7,
      items: [
        row({
          id: 'front-yard',
          section: 'yard_requirements',
          zrSection: '23-45',
          itemDescription: 'Front Yard',
          permittedRequired: 'N/A',
          proposed: '',
          result: 'incomplete',
          evaluationMode: 'manual_input',
        }),
        row({
          id: 'side-yard',
          section: 'yard_requirements',
          zrSection: '23-462',
          itemDescription: 'Side Yard',
          permittedRequired: 'N/A',
          proposed: '',
          result: 'incomplete',
          evaluationMode: 'manual_input',
        }),
        row({
          id: 'rear-yard',
          section: 'yard_requirements',
          zrSection: '23-47 & 23-541',
          itemDescription: 'Rear Yard',
          permittedRequired: "30'-0\" minimum at interior lot portion only. No rear yard required within 100' of corner.",
          proposed: '',
          result: 'incomplete',
          status: 'guidance',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'window-lot-line',
          section: 'yard_requirements',
          zrSection: '23-861',
          itemDescription: 'Minimum distance between windows and lot lines',
          permittedRequired: "30'-0\"",
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
      ],
    },
    {
      id: 'height-setback',
      reportId,
      key: 'height_setback',
      title: 'Height & Setback',
      description: 'Base plane, street wall articulation, height, stories, and setback checks.',
      sortOrder: 8,
      items: [
        row({
          id: 'base-plane',
          section: 'height_setback',
          zrSection: '12-10',
          itemDescription: 'Base Plane Elevation',
          permittedRequired: 'TBD after survey',
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
          notes: 'Workbook uses a separate Base Plane Calculation sheet.',
        }),
        row({
          id: 'street-wall-articulation',
          section: 'height_setback',
          zrSection: '141-23(a)',
          itemDescription: "Street wall articulation for site widths exceeding 100'",
          permittedRequired:
            "At least 70 percent of aggregate street wall width located within 8'-0\" of street line; projection/recess area review required.",
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
        }),
        row({
          id: 'min-base-height',
          section: 'height_setback',
          zrSection: '141-23(a)',
          itemDescription: 'Minimum base height',
          permittedRequired: "15'-0\" minimum",
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'max-base-height-corner',
          section: 'height_setback',
          zrSection: '141-23(b)',
          itemDescription: "Maximum base height within 75' of corner",
          permittedRequired: "105'-0\"",
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'max-building-height',
          section: 'height_setback',
          zrSection: '141-23(b)',
          itemDescription: 'Maximum building height',
          permittedRequired: "165'-0\"",
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'max-stories',
          section: 'height_setback',
          zrSection: '141-23(b)',
          itemDescription: 'Maximum number of stories',
          permittedRequired: '16 stories',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'initial-setback',
          section: 'height_setback',
          zrSection: '141-23(b)',
          itemDescription: 'Initial setback',
          permittedRequired: "10'-0\" for wide street; Jerome Ave is 100'-0\"",
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'elevated-rail-articulation',
          section: 'height_setback',
          zrSection: '141-23(c)',
          itemDescription: 'Street wall articulation along elevated rail structure',
          permittedRequired:
            'Minimum 20 percent of surface area above second story or 30 feet must recess/project at least three feet; projection depth must not exceed three feet.',
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
        }),
      ],
    },
    {
      id: 'parking',
      reportId,
      key: 'parking',
      title: 'Parking',
      description: 'Accessory parking and bicycle parking checks.',
      sortOrder: 9,
      items: [
        row({
          id: 'residential-parking',
          section: 'parking',
          zrSection: '36-35 / 25-251',
          itemDescription: 'Required accessory parking UG-II',
          permittedRequired: 'None required for income-restricted housing units in Transit Zones',
          proposed: '',
          result: 'manual_review_required',
          status: 'guidance',
          evaluationMode: 'manual_review',
          notes: 'Confirm income-restricted units and transit zone applicability.',
        }),
        row({
          id: 'cf-parking',
          section: 'parking',
          zrSection: '36-21',
          itemDescription: 'Required accessory parking UG-IIIA',
          permittedRequired: 'None required',
          proposed: '',
          result: 'incomplete',
          evaluationMode: 'manual_input',
        }),
        row({
          id: 'bike-ug-ii',
          section: 'parking',
          zrSection: '36-711',
          itemDescription: 'Bicycle parking - UG-II',
          permittedRequired: '1 per 2 dwelling units',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'bike-ug-iiia',
          section: 'parking',
          itemDescription: 'Bicycle parking - UG-IIIA',
          permittedRequired: '1 per 10,000 sf of floor area',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
      ],
    },
    {
      id: 'street-trees',
      reportId,
      key: 'street_trees',
      title: 'Street Trees',
      description: 'Street tree requirement and proposed tree/payment strategy.',
      sortOrder: 10,
      items: [
        row({
          id: 'street-trees-required',
          section: 'street_trees',
          zrSection: '23-03',
          itemDescription: 'Required street trees',
          permittedRequired: "1 per 25' of street frontage",
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
      ],
    },
    {
      id: 'quality-housing',
      reportId,
      key: 'quality_housing',
      title: 'Quality Housing',
      description: 'Drawing-dependent Quality Housing checks.',
      sortOrder: 11,
      items: [
        row({
          id: 'refuse-storage',
          section: 'quality_housing',
          zrSection: '28-12',
          itemDescription: 'Refuse storage and disposal',
          permittedRequired: "Refuse room minimum 12 sf per floor; no dimension less than 3'-0\"",
          proposed: '',
          result: 'incomplete',
          status: 'guidance',
          evaluationMode: 'manual_input',
        }),
        row({
          id: 'corridor-daylight',
          section: 'quality_housing',
          zrSection: '28-14',
          itemDescription: 'Daylight in corridors',
          permittedRequired: 'Minimum 20 sf of glazing visible from vertical circulation core',
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
        }),
        row({
          id: 'recreation-space',
          section: 'quality_housing',
          zrSection: '28-21',
          itemDescription: 'Required recreation space',
          permittedRequired: '2.8% of total residential floor area',
          proposed: '',
          result: 'incomplete',
          status: 'calculated',
          evaluationMode: 'formula_check',
        }),
        row({
          id: 'recreation-standards',
          section: 'quality_housing',
          zrSection: '28-22',
          itemDescription: 'Standards for recreation space',
          permittedRequired: "Outdoor minimum 225 sf and 15'-0\"; indoor minimum 300 sf and 15'-0\"; windows minimum 9.5% of floor area",
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
        }),
        row({
          id: 'planting-areas',
          section: 'quality_housing',
          zrSection: '28-23',
          itemDescription: 'Planting areas',
          permittedRequired: 'Planting between street line and street wall',
          proposed: '',
          result: 'incomplete',
          status: 'guidance',
          evaluationMode: 'manual_input',
        }),
        row({
          id: 'density-per-corridor',
          section: 'quality_housing',
          zrSection: '28-31',
          itemDescription: 'Density per corridor',
          permittedRequired: 'Less than 10 dwelling units served per corridor',
          proposed: '',
          result: 'incomplete',
          status: 'guidance',
          evaluationMode: 'manual_input',
        }),
        row({
          id: 'special-open-space',
          section: 'quality_housing',
          zrSection: '141-33',
          itemDescription: 'Special open space provisions',
          permittedRequired: "Various options including 3'-0\" minimum planting strip",
          proposed: '',
          result: 'manual_review_required',
          status: 'manual_review_required',
          evaluationMode: 'manual_review',
        }),
      ],
    },
  ],
  manualFlags: [
    {
      id: 'flag-proposed-values',
      reportId,
      title: 'Proposed values are architect inputs',
      description:
        'The address can seed site facts and permitted requirements, but proposed FAR, area, height, yards, parking, and Quality Housing values must come from the project design team.',
      severity: 'high',
      reference: 'Workbook proposed column',
    },
    {
      id: 'flag-special-district',
      reportId,
      title: 'Special district interpretation requires review',
      description:
        'Street-wall, frontage, transparency, elevated-rail, MIH, and Quality Housing provisions depend on drawings and current zoning text.',
      severity: 'high',
      reference: 'ZR 141',
    },
  ],
  references: [
    {
      id: 'ref-workbook',
      reportId,
      label: 'Uploaded zoning-analysis workbook',
      source: workbookReferenceNotes.file,
      notes: workbookReferenceNotes.workflowSummary,
    },
    {
      id: 'ref-zr',
      reportId,
      label: 'NYC Zoning Resolution',
      source: 'NYC Department of City Planning',
      url: 'https://zoningresolution.planning.nyc.gov/',
    },
    {
      id: 'ref-district-guide',
      reportId,
      label: 'NYC Planning Zoning Districts Guide',
      source: 'NYC Department of City Planning',
      url: 'https://www.nyc.gov/content/planning/pages/zoning/zoning-districts-guide',
    },
  ],
};
